package com.geoinfo.util;

public enum EImportFileType {
    FILE_CLIENTE_GEOINFO,
    FILE_ESTABELECIMENTO_GEOINFO,
    FILE_VENDEDOR_GEOINFO,
    FILE_PRODUTO_GEOINFO,
    FILE_FORMAPAGAMENTO_GEOINFO,
    FILE_VENDA_GEOINFO,
    FILE_XML_NFE_GEOINFO;
}
